# Generated by Django 4.2.5 on 2023-10-19 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='arabian_product',
            field=models.BooleanField(default=True),
        ),
    ]
